### ISSUE TITLE
js-ipfs v0.24.0 pre-release testing

### ISSUE THREAD

**Issue by diasdavid** [orbitdb/ipfs-log#108]
Hi @haadcode! We are about to release the next version of js-ipfs. I've just ran the tests with the new release and it seems it will require just one single migration: using the new simplified init set up.

This was already a change on v0.23.0, so I guess ipfs-daemon never got up to date.

The error:

```
/Users/koruza/code/ipfs-log/node_modules/ipfs-daemon/src/ipfs-node-daemon.js:83
                this._daemon.load((err) => {
                             ^

TypeError: this._daemon.load is not a function
    at _daemon.config.set (/Users/koruza/code/ipfs-log/node_modules/ipfs-daemon/src/ipfs-node-daemon.js:83:30)
    at waterfall (/Users/koruza/code/js-ipfs/node_modules/datastore-fs/src/index.js:172:17)
    at /Users/koruza/code/js-ipfs/node_modules/async/internal/parallel.js:39:9
    at /Users/koruza/code/js-ipfs/node_modules/async/internal/once.js:12:16
    at replenish (/Users/koruza/code/js-ipfs/node_modules/async/internal/eachOfLimit.js:59:25)
    at iterateeCallback (/Users/koruza/code/js-ipfs/node_modules/async/internal/eachOfLimit.js:49:17)
    at /Users/koruza/code/js-ipfs/node_modules/async/internal/onlyOnce.js:12:16
    at /Users/koruza/code/js-ipfs/node_modules/async/internal/parallel.js:36:13
    at /Users/koruza/code/js-ipfs/node_modules/write-file-atomic/index.js:60:11
    at LOOP (/Users/koruza/code/js-ipfs/node_modules/slide/lib/chain.js:7:26)
    at /Users/koruza/code/js-ipfs/node_modules/slide/lib/chain.js:18:7
    at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR! Test failed.  See above for more details.
```

To learn how to spawn a node today, you can check the README here: https://github.com/ipfs/js-ipfs#create-a-ipfs-node-instance

**Comment by haadcode** [comment]
Hi @diasdavid, thanks for reporting so long ago! We've made a lot of progress since and the fresh version `4.0.0` runs with [js-ipfs@0.26.0](https://github.com/orbitdb/ipfs-log/blob/master/package.json#L25) really nicely! 😄 👍 

Make sure to check out the [latest benchmarks](https://github.com/orbitdb/ipfs-log/tree/master/benchmarks) too. We're looking at ~5k appends/s and ~2k joins/s with the latest version. Just earlier this year we were at <1k appends and ~100 joins/s 😄 We've come far since and IPFS is saving those objects like crazy! Great job! 😄 👍 ❤️ 

Gonna close this issue as it's mostly out of date. ipfs-log should be again testable with js-ipfs release if you want to make sure there's extra test coverage upon release 😃
