### ISSUE TITLE
error in entry.js

### ISSUE THREAD

**Issue by mccoysc** [orbitdb/ipfs-log#180]
static findChildren(entry, values) {
    var stack = []
    var parent = values.find((e) => Entry.isParent(entry, e))
    var prev = entry
    while (parent) {
      stack.push(parent)
      prev = parent
      parent = values.find((e) => Entry.isParent(prev, e))
    }
    stack = stack.sort((a, b) => a.clock.time > a.clock.time)
    return stack
  }

maybe "a.clock.time > a.clock.time" should be "a.clock.time > b.clock.time"?

**Comment by haadcode** [comment]
Thanks @mccoysc for reporting the issue! It was spotted during a recent PR and is fixed in master (see https://github.com/orbitdb/ipfs-log/blob/master/src/entry.js#L203). However, the master hasn't been published to npm yet which I assume is where you see the bug. If this is a crucial fix for you, I recommend to use the module from master until we have it in npm.
