### ISSUE TITLE
It would be great to have CI on this module

### ISSUE THREAD

**Issue by diasdavid** [orbitdb/ipfs-log#94]

**Comment by haadcode** [comment]
https://circleci.com/gh/haadcode/ipfs-log

**Comment by haadcode** [comment]
Has always been there. Is there something specific you're looking for?

**Comment by haadcode** [comment]
Would adding a badge to the README be what is needed here? I'm assuming you opened this due to not finding the CI.

**Comment by diasdavid** [comment]
Having it on the README would be helpful, yes. Adding Travis + Saucelabs will give you more guarantees as circle caching mechanism does make it fast, but it has a lot of false positives.

**Comment by haadcode** [comment]
I've had this running on CircleCI for almost a year now without major hiccups. I've been happy with CircleCI. The false positives due to caching are annoying I agree, but I've found it makes me pay more attention and double check that the build is fine, which is a good thing.

I'll add the badge to the README, I think that makes it obvious to find the CI.

I don't feel there's a need to absolutely add more on the CI side, but if you think adding more CI platforms adds value to the repository, I'd be happy to take a look at a PR.

**Comment by haadcode** [comment]
We've been quite happy with [CircleCI](https://github.com/orbitdb/ipfs-log#ipfs-log) for the past year. Going to close this for now. If you feel that we should add Travis or other CI integrations, feel free to re-open the issue or a PR! Thanks for reporting it long time ago 😄 👍
